### ISSUE TITLE
评论无法显示

### ISSUE THREAD

**Issue by anyiweb** [bhaoo/Cuckoo#127]

**Comment by bhaoo** [comment]
是直接替代文件的形式更新的么

**Comment by anyiweb** [comment]
> 是直接替代文件的形式更新的么

是的

**Comment by anyiweb** [comment]
> 是直接替代文件的形式更新的么

已解决，我在主题设置页面直接恢复了，没有重新复制粘贴，感谢！（可以删除这个issue了~）
