### ISSUE TITLE
文章随机图片使用自定义API问题

### ISSUE THREAD

**Issue by 2209901700** [bhaoo/Cuckoo#13]
我想问一下，文章随机置顶图片默认的其实就不错，但是图片太少了，想用自己的。但更换为自己的API后所有文章只显示一个图片，换一个API后直接不显示了。。。
希望曾进完善。

**Comment by 2209901700** [comment]
或者作者大大增多一点默认API图片也不错呢。

**Comment by rsj123** [comment]
可以尝试自己改那个模板文件，我自己改了的是可以正常显示的，可能修改的逻辑有问题。另外不知道po主是否有意一起维护一个随机图api

**Comment by 2209901700** [comment]
@rsj123 哦，嗯，谢谢你！但是现在我暂时不想做随机图片API了。十分对不起＞人＜了。

**Comment by rsj123** [comment]
这是本人目前在维护的api
https://php.vg/api/
https://php.vg/api/?type=oss
（第二个为webp格式

**Comment by bhaoo** [comment]
你可以通过给你的api加上变量 {rand} 进行"硬核"换图哦！
例如：api.xxx.xxx/images?{rand}

**Comment by 2209901700** [comment]
@bhaoo 好的，谢谢你。
