### ISSUE TITLE
关于萌备的超链接

### ISSUE THREAD

**Issue by 30266-Official** [bhaoo/Cuckoo#130]
前几天申请了萌备，然后在【基础设置】的【萌国ICP备案】填写了8位萌备号，并且在网站底端可以正确显示。今早收到了萌备工作人员的邮件，工作人员认为我没有按要求悬挂萌备号：

>我们今日致信于您是因为在网站审核寻得了不正确的萌备悬挂。
萌备请求所有申请的萌主在主页上放置注册号的悬挂，即一个指向萌备记录的超链接。

我认为，这可能是由于模版的超链接方式导致的：

萌备希望的：[萌ICP备20240001号](https://icp.gov.moe/?keyword=20240001)
通过模版添加的：[萌ICP备](https://icp.gov.moe/)[20240001](https://icp.gov.moe/?keyword=20240001)号（前面萌ICP备和后面备案号是两个独立的、指向不同网页的超链接，并且“号”未超链接）

**Comment by LoCCai** [comment]
emmm，这么神奇的吗，，我的博客是去年申请的，但是一直正常。估计是萌备那边改了查询策略还是？
