### ISSUE TITLE
侧栏页面点击两次会出现问题

### ISSUE THREAD

**Issue by 2209901700** [bhaoo/Cuckoo#14]
添加了侧栏页面。网站没有配置伪静态。
在点击一个侧栏页面后，再次点击随机的一个侧栏页面会在原本的www.xxx.com/index.php/aaa.html变成www.xxx.com/index.php/index.php/xxx.html。直接导致找不到文章页面。

我的站点地址:https://llyt.me/

**Comment by bhaoo** [comment]
可以发下你的自定义侧边栏填写的内容嘛？

**Comment by 2209901700** [comment]
[{
        "name":"分类",
        "link":"#",
        "icon":"view_list",
        "type":"2"
       },{
        "name":"归档",
        "link":"#",
        "icon":"access_time",
        "type":"1"
       },{
        "name":"页面",
        "link":"#",
        "icon":"view_carousel",
        "type":"3"
       },{
         "type":"5"
       },{
         "type":"6"
       

},{
 "name":"留言天地",
 "link":"index.php/liuyan.html",
 "icon":"&#xe435;",
 "type":"0"


},{
 "name":"友人帐",
 "link":"index.php/yourz.html",
 "icon":"links",
 "type":"0"


 
},{
 "name":"MY 萌站",
  "link":"#",
  "icon":"&#xe3af",
  "type":"4",
  "list": [{
 "name": "龙柳夜童欣",
  "link": "https://www.lly.recipes/"
  },{
    "name": "随风动漫",
    "link": "http://loliloli.loli.fund/"
  },{
    "name": "储存",
    "link": "http://lly.lingdi.uk/"
  }]


}]

**Comment by bhaoo** [comment]
把 "link":"index.php/liuyan.html" 修改为 "link":"https://llyt.me/liuyan.html" ，其他的也依照这个进行修改试试看吧

**Comment by 2209901700** [comment]
@bhaoo 好的，我试试

**Comment by 2209901700** [comment]
嗯，暂时看起来好了，作者大大真厉害。

**Comment by bhaoo** [comment]
那我这边关闭了哦
