### ISSUE TITLE
建议自定义抽屉时支持第三方链接引用icon功能

### ISSUE THREAD

**Issue by cfandora** [bhaoo/Cuckoo#19]
如题，现在使用链接的话，会这样显示

![jietu](https://user-images.githubusercontent.com/26035787/121819590-77c33100-ccc0-11eb-98f1-f8d7d9c259cd.png)

**Comment by bhaoo** [comment]
可以说明更详细些么，主题框架为MDUI，引用的也是[mdui-icon](https://www.mdui.org/docs/material_icon)，你可以自行添加的哦。
