### ISSUE TITLE
侧边栏只有电脑上chrome浏览器能展开

### ISSUE THREAD

**Issue by NobeKanai** [bhaoo/Cuckoo#2]
我用edge和手机上的常见浏览器（包括chrome）都无法展开侧边栏。

**Comment by bhaoo** [comment]
是可以的哦～你是不是设置到什么了？

**Comment by NobeKanai** [comment]
> 是可以的哦～你是不是设置到什么了？

不清楚啊， 应该是我的问题， 我再看看吧
