### ISSUE TITLE
2.0中过多模糊导致低性能设备出现掉帧问题

### ISSUE THREAD

**Issue by Henry14all** [bhaoo/Cuckoo#20]
在2.0中，开发者加了很多模糊，但这样会导致在性能不好的设备上或设备性能差的时后出现动画卡顿、掉帧现象。

我在MDUI群问了厉害的人，他们分析说只要去除背景模糊即可。

![image](https://user-images.githubusercontent.com/59821569/130817112-72d55b34-3b58-4ffb-9175-bf3b2293e264.png)

目前限于个人能力我没法修改代码，因此提交此issue希望开发者能改进一下，变成如下这样：

导航栏中添加关闭模糊按钮，默认开启模糊，如果用户出现卡顿可以手动关闭。有条件的话可以试试写段代码根据性能自动开关模糊。

附：大佬给的代码

`body > .background .index-filter {
  backdrop-filter: initial!important;
}`

**Comment by DFFZMXJ** [comment]
![允悲](https://user-images.githubusercontent.com/35987451/130819870-2d30e24f-91d5-4836-b599-b01859c3c0de.png)

补充一下，其实在米 10 上用 Chrome 92 访问很流畅，或许是电脑的图形性能不太好……

电脑 CPU 是 Intel i3-4005U，内存 8G DDR3，显卡是核显。

**Comment by bhaoo** [comment]
由于 backdrop-filter 属性确实对性能有些要求hhh，所以以后 Cuckoo 只在动画过程中需要使用高斯模糊时候再使用 backdrop-filter 了，背景图片就不用 backdrop-filter 属性了
