### ISSUE TITLE
不兼容某些插件

### ISSUE THREAD

**Issue by anyiweb** [bhaoo/Cuckoo#23]
**问题出处：**
2.0版本主题不兼容插件AliceStyle
这个问题出现在哪个功能上？

**问题结果：**
插件启动后设置无效
触发问题后造成了什么效果及影响？

**预期结果：**

你觉得这个功能该怎么样？
影响使用
**问题复现：**

你是怎么触发这个问题的？
开启AliceStyle插件后不管怎么设置均无效，看板娘（live2D）完全失效。1.05版本都支持的呢
**配置与环境：**

- 问题页面： 任何页面
- PHP 版本：PHP7.3
- 数据库类型 / 版本：MySQL5.5.62
- Typecho 版本：1.1
- 主题版本：2.0（R
- 使用的插件：AliceStyle 项目地址：https://github.com/racns/AliceStyle
- 浏览器：google chrome 91.0.4472.164（正式版本） （64 位）
**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**
AliceStyle插件的“返回顶部”及“live2D酱”无法兼容（设置无效）
提供尽可能多的相关信息。

**Comment by bhaoo** [comment]
测试了版本 3.4 的，目前是有兼容的，【返回顶部】和【live2D酱】都正常显示和使用。
