### ISSUE TITLE
后台侧栏头像在 Safari 上被错误拉伸

### ISSUE THREAD

**Issue by InariHimeko** [bhaoo/Cuckoo#24]
**问题出处：**

 后台侧栏头像

**问题结果：**

后台侧栏头像在 Safari 浏览器上被错误拉伸

**问题复现：**

使用 Safari 浏览器

**配置与环境：**

- PHP 版本：
- 数据库类型 / 版本：
- Typecho 版本：1.1 (17.10.30)
- 主题版本：2.0
- 使用的插件：无
- 浏览器：Safari 14.1.2

**截图（若有）**

<img width="239" alt="image" src="https://user-images.githubusercontent.com/62369552/131212145-dbc5e240-ac48-4eee-826b-3f1f1af7a8b1.png">

**补充信息：**

推测是 css 指令 Webkit 不支持所致

**Comment by bhaoo** [comment]
已经修复了哦，详情看[这里](https://github.com/bhaoo/Cuckoo/commit/9626e43b3e66f443f323bb96e8ed276fd0afed96)
