### ISSUE TITLE
高斯模糊 backdrop-filter: blur 在非 Chromium 内核上不被显示

### ISSUE THREAD

**Issue by InariHimeko** [bhaoo/Cuckoo#25]
**问题出处：**

2.0 版本高斯模糊

**问题结果：**

非 Chromium 内核浏览器不显示高斯模糊效果，截图在下面

**预期结果：**

不同浏览器相同效果

**配置与环境：**

- 问题页面：
- PHP 版本：
- 数据库类型 / 版本：
- Typecho 版本：1.1 (17.10.30)
- 主题版本：2.0
- 使用的插件：无
- 浏览器： Safari, Firefox

**截图（若有）**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62369552/131213166-e07d98ee-0531-4242-9834-eb24d4d058c7.png">

左中右分别为 Safari Firefox Edge，可见 Safari 和 Firefox 都无高斯模糊效果

**补充信息：**

问题应该出在 backdrop-filter: blur 仅在 Chromium 内核默认开启
Firefox 可以通过 config 开启但是默认关闭，现实中会开启的人应该非常少
Safari 则需要加前缀 -webkit-backdrop-filter

**Comment by bhaoo** [comment]
Firefox目前还[不兼容backdrop-filter](https://caniuse.com/?search=backdrop-filter) emmmm
Safari的话我去加个前缀 -webkit-backdrop-filter！

**Comment by bhaoo** [comment]
修好啦！
---
你可以在“主题设置-高级设置-更多CSS”中添加下列代码解决问题哦！

```css
.index-img-media:hover .index-card-filter {
  -webkit-backdrop-filter: blur(7px);
}
```

再修点BUG后续就整合到v2.0.1上啦！
