### ISSUE TITLE
建议优化首页图片放大时的圆角效果

### ISSUE THREAD

**Issue by InariHimeko** [bhaoo/Cuckoo#26]
**这个想法是哪个方面的？**

UI 界面 / 用户体验

**这个想法要改进什么？**

鼠标移动到图片上时图片放大阶段图片四角会由圆角突然变成直角，再变为圆角。比较影响视觉体验

https://user-images.githubusercontent.com/62369552/131213540-ea52846a-8e85-49e2-ba79-83c816987726.mov

**这个想法能为项目提供什么帮助？**

优化视觉效果，提升强迫症患者满意度

**是否有具体的实现思路？**

暂无

**补充信息：**

**Comment by InariHimeko** [comment]
Update:

我发现只在 Safari 上才会出现这种问题
Safari 垃圾.jpg

**Comment by bhaoo** [comment]
修好啦！
---
你可以在“主题设置-高级设置-更多CSS”中添加“.index-card{transform: scale(1);}”解决问题哦！

再修点BUG后续就整合到v2.0.1上啦！

**Comment by InariHimeko** [comment]
thx!
