### ISSUE TITLE
2.0丢失了部分1.0的功能

### ISSUE THREAD

**Issue by TangYB945** [bhaoo/Cuckoo#28]
**问题出处：**

如文章不支持解析表情包，文章目录树不加载，以及哔哩哔哩追番失效等问题

**问题结果：**

触发问题后造成了什么效果及影响？
导致文章页面出现未解析出表情包，导致文章中不显示目录，导致哔哩哔哩获取不到番剧（2.0中无缓存文件夹，（确信

**预期结果：**

你觉得这个功能该怎么样？
这些功能很好，就是被移除了？

**问题复现：**

你是怎么触发这个问题的？

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：5.4
- 数据库类型 / 版本：MySQL 5.5.62
- Typecho 版本：1.1 (17.10.30)
- 主题版本：（Release 标注的版本号，开发版则写 Dev.）
- 使用的插件：2.0.0
- 浏览器：（浏览器名称及版本号）

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by bhaoo** [comment]
表情包可以解析了哦~文章目录也回来啦！
