### ISSUE TITLE
一个关于随机文章图源的建议

### ISSUE THREAD

**Issue by CX4A3** [bhaoo/Cuckoo#3]
作者您好，感谢您带来这优秀的主题。
在使用随机文章图源这个功能时，因为我并不太想走OMGAPI，所以我更希望于使用我自有的白嫖TX云的CDN作为随机图源，然而在自定义随机图CDN中，我没有发现有能替换随机数的变量，最后我通过修改主题源代码实现了这一特性。
我表达能力并不是太好，但是如果能让用户这样设置“CDN”字段，我相信会更棒：
https://*****.file.myqcloud.com/%rand%.png
如果能让用户设置随机数数字范围那更好~
再次感谢您带来的优秀主题，这一点小小的建议希望作者能够采纳，谢谢。

**Comment by bhaoo** [comment]
好的，下一个版本我会改进的！谢谢你提出的建议！

**Comment by bhaoo** [comment]
已经提交Commit了，感谢你的反馈！
