### ISSUE TITLE
网站右侧友链和友链页报错

### ISSUE THREAD

**Issue by hyb-oyqq** [bhaoo/Cuckoo#32]
**问题出处：**
网站右侧友链和友链页报错
Warning: shuffle() expects parameter 1 to be array, null given in /www/wwwroot/ouyangqiqi.cn/usr/themes/Cuckoo/functions.php on line 438

Warning: count(): Parameter must be an array or an object that implements Countable in /www/wwwroot/ouyangqiqi.cn/usr/themes/Cuckoo/functions.php on line 440 

**配置与环境：**

- 问题页面：https://ouyangqiqi.cn/index.php/links.html
- PHP 版本：PHP7.4
- 数据库类型 / 版本：MySQL 5.7.33
- Typecho 版本：1.2 (18.10.23)
- 主题版本：2.0.0
- 使用的插件：Access,ActivatePowerMode,CommentToMail,ExSearch,Links,Pio,Smilies,ViewsCounter

- 浏览器：Chrome 92.0.4515.131

**截图（若有）**

![image](https://user-images.githubusercontent.com/35864297/132176715-66f380f8-e463-4435-b698-983e18e4fd80.png)

**Comment by bhaoo** [comment]
需要使用新的Links插件哦！

**Comment by bhaoo** [comment]
已经补充到releases啦！[点这里！](https://github.com/bhaoo/Cuckoo/releases/tag/2.0.0)

**Comment by hyb-oyqq** [comment]
上传插件后后台无法正常启用怎么办QAQ

**Comment by hyb-oyqq** [comment]
> 已经到了发布啦！[点这里！](https://github.com/bhaoo/Cuckoo/releases/tag/2.0.0)

上传插件后后台无法正常启用怎么办QAQ而且好像寒泥的官网只更新到1.1.1吧。。。QQ群我大号小号都申请加群了就没通过过，1.0的时候就申请了

**Comment by bhaoo** [comment]
qq群没过么 你qq多少哇

**Comment by hyb-oyqq** [comment]
> qq群没过么 你qq多少哇
> 我刚刚添加好友 发现你把添加好友权限关了hhh

已经开了已经开了qwqQQ号是1512383570
