### ISSUE TITLE
Notice: Undefined variable: content in /usr/local/nginx/html/usr/themes/Cuckoo/functions.php on line 406

### ISSUE THREAD

**Issue by somes** [bhaoo/Cuckoo#36]
**问题出处：**
首页底部

**问题结果：**
Notice: Undefined variable: content in /usr/local/nginx/html/usr/themes/Cuckoo/functions.php on line 406

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.2.20
- 数据库类型 / 版本：MySQL 5.7.13
- Typecho 版本：1.1 (17.10.30)
- 主题版本：（Release 标注的版本号，开发版则写 Dev.）正式版 v2.0.0
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**
[https://z3.ax1x.com/2021/09/23/4aTUwd.png](url)

提供一个此问题触发的截图或报错信息。若没有，则留空。
Notice: Undefined variable: content in /usr/local/nginx/html/usr/themes/Cuckoo/functions.php on line 406

提供尽可能多的相关信息。

**Comment by bhaoo** [comment]
修复了哦~[看这里哟！](https://github.com/bhaoo/Cuckoo/commit/088edf362788443b8067aa0a33d0163c2cc1a37b)
