### ISSUE TITLE
请问支持1.2.0的typecho吗？

### ISSUE THREAD

**Issue by xiongminghao** [bhaoo/Cuckoo#39]
我把typecho从正式版更新到了开发版，发现cuckoo设置外观打不开了
提示Argument 1 passed to _t() must be of the type string, null given, called in /www/wwwroot/nanxiaoxiong.com/usr/themes/Cuckoo/libs/setting.php on line 86

**配置与环境：**

- 问题页面：https://nanxiaoxiong.com/admin/options-theme.php
- PHP 版本：7.4
- 数据库类型 / 版本：mysql5.6
- Typecho 版本：1.2.0
- 主题版本：2
- 使用的插件：全关了
- 浏览器：microsoft edge

**Comment by scwunai** [comment]
把79行形参$default=NULL改成$default=“”就可以了

**Comment by bhaoo** [comment]
我在Typecho **1.2 (18.1.29)** 和 **1.2 (18.10.23)** 和 **1.2.0** 的版本下都没有复现出问题哦

**Comment by Mizobrook-kan** [comment]
我复现了这个问题，includes/setting.php的108行，$default是NULL。
`$config->textarea('drawerContact', '联系方式', '在此填写您的联系方式，最多仅能展示6个。').`
**配置与环境：**

- PHP 8.1.3
- mysql 8.0.25
- Typecho 版本：1.2.0
- 主题版本：2
- 插件：关闭
- 浏览器：chrome

**Comment by bhaoo** [comment]
可以支持 1.2.0 啦！解决方法在这里！-> https://github.com/bhaoo/Cuckoo/commit/45db3799cf9c50a1f33ec1036a004ab1ddee32de
