### ISSUE TITLE
网页时光机总是触发“请勿删除/修改版权，请尊重独立开发者劳动成果”

### ISSUE THREAD

**Issue by Lapis-Apple** [bhaoo/Cuckoo#42]
**问题出处：**

版权保护功能？

**问题结果：**

web.archive.org 抓取的网页在浏览的时候全部触发这个保护。

**预期结果：**

正常查看缓存后的往期网页。

**问题复现：**

在 web.archive.org 查看使用 Cuckoo 的网页。

**配置与环境：**

- 问题页面：https://web.archive.org/web/20220227034457/https://laple.me/
- PHP 版本：7.3
- 数据库类型 / 版本：MariaDB
- Typecho 版本：1.2 (19.05.09)
- 主题版本：2.0.0
- 使用的插件：HoerMouse Links SmartSpam
- 浏览器：Chrome 98

**截图（若有）**

![image](https://user-images.githubusercontent.com/62464927/155867325-a2748d00-2371-470b-b91e-0748bdc206df.png)

**补充信息：**

None

**Comment by rsj123** [comment]
看起来像是 archive 导致js缺失/未正常加载导致的
