### ISSUE TITLE
对 Typecho 1.2.0 和 PHP 8.0 的支持问题

### ISSUE THREAD

**Issue by TC-Mits-Qine** [bhaoo/Cuckoo#44]
> 反馈前请确认你的 **CDN或浏览器缓存已经清除**，你没有 **修改相关源代码** ，若你已经确认为项目中的问题，请删除这段文本，继续完成你的反馈

**问题出处：**

博客主页 以及 设置外观 (options-theme.php)。

**问题结果：**

主页加载异常，设置外观页面无法打开。

**预期结果：**

页面正常加载，可正常进行设置。

**问题复现：**

升级 PHP 8.0 和 Typecho 1.2.0

**配置与环境：**

- 问题页面：下方附上保存的网页文件
- PHP 版本：PHP 8.0
- 数据库类型 / 版本：MySQL 5.6.50
- Typecho 版本：1.2.0 最新开发版
- 主题版本：2.0.0
- 使用的插件：禁用所有插件后问题依旧，且 Links 友情链接插件 无法启用，错误号：42S01
- 浏览器：Chrome 99.0.4844.84

**截图**
![image](https://user-images.githubusercontent.com/32544907/160598595-099fc8f8-fca4-4a01-8d9d-3b73358bc48b.png)

**补充信息：**

主页左上报错信息
```bash
Deprecated: Required parameter $options follows optional parameter $display in /www/wwwroot/kokodayo.site/usr/themes/Cuckoo/libs/setting.php on line 51

Deprecated: Required parameter $options follows optional parameter $display in /www/wwwroot/kokodayo.site/usr/themes/Cuckoo/libs/setting.php on line 91

Warning: Undefined variable $output in /www/wwwroot/kokodayo.site/usr/themes/Cuckoo/functions.php on line 169
```

主页底部报错信息
```bash
Warning: Undefined variable $content in /www/wwwroot/kokodayo.site/usr/themes/Cuckoo/functions.php on line 406
```
options-theme.php 页面报错信息
```bash
_t(): Argument #1 ($string) must be of type string, null given, called in /www/wwwroot/kokodayo.site/usr/themes/Cuckoo/libs/setting.php on line 86
```
出错时的博客主页
[kokodayo.site.zip](https://github.com/bhaoo/Cuckoo/files/8370717/kokodayo.site.zip)

**Comment by bhaoo** [comment]
修好啦！可以看看这里！
https://github.com/bhaoo/Cuckoo/commit/45db3799cf9c50a1f33ec1036a004ab1ddee32de
https://github.com/bhaoo/Cuckoo/commit/f70d15dfc647d30cd38f615a27a15505692a3bcb
https://github.com/bhaoo/Cuckoo/commit/60cddaadfac351ae924f6905354a1561aa7512b5
