### ISSUE TITLE
使用插件JWPlayer的问题

### ISSUE THREAD

**Issue by cfandora** [bhaoo/Cuckoo#45]
> 反馈前请确认你的 **CDN或浏览器缓存已经清除**，你没有 **修改相关源代码** ，若你已经确认为项目中的问题，请删除这段文本，继续完成你的反馈

**问题出处：**

使用了 [JWPlayer](https://github.com/jzwalk/JWPlayer) 的页面

**问题结果：**

第一次打开页面时会卡在“播放器载入中...”，刷新后播放器才加载

**预期结果：**

打开时直接加载播放器

**问题复现：**

使用了JWPlayer的页面，第一次打开都会这样

**配置与环境：**

- 问题页面：https://dg.cfandora.xyz/archives/3/
- PHP 版本：7.4
- 数据库类型 / 版本：MySQL 5.7.37
- Typecho 版本：1.1 (17.10.30)
- 主题版本：正式版v2.0.0
- 使用的插件：JWPlayer
- 浏览器：chrome 99.0.4844.84

**截图（若有）**

![QQ截图20220330113510](https://user-images.githubusercontent.com/26035787/160746352-75982400-874c-4f08-8c87-2ee1a48d9bd5.png)

**Comment by bhaoo** [comment]
JWPlayer 加载时会在播放器前引用其 JS 文件
```html
<script type="text/javascript">
  window.jwplayer || document.write('<script type="text/javascript" src="http://xxx.com/usr/plugins/JWPlayer/player/jwplayer.js"><\/script>')
</script>
```

但是 PJAX 不允许重载内容包含 document.write（Script contains document.write. Can’t be executed correctly. Code skipped）

因此如果想要果断直接地解决问题可以在 `includes/header.php` 中第 36 行后加上

```html
<script type="text/javascript">
    window.jwplayer || document.write('<script type="text/javascript" src="http://xxx.com/usr/plugins/JWPlayer/player/jwplayer.js"><\/script>')
</script>
```

以此来解决问题
