### ISSUE TITLE
版权所有无法自定义

### ISSUE THREAD

**Issue by only-matthew** [bhaoo/Cuckoo#46]
**这个想法是哪个方面的？**

功能改进

现有内容的优化 / 新增功能 / UI 界面 / 用户体验

目前底部版权信息只能是用户id和2022

**这个想法要做到什么？**
可以自定义底部年份和版权所有

**这个想法能为项目提供什么帮助？**
给用户更好的体验

**是否有具体的实现思路？**
无

**补充信息：**

版权所有是个人id而且不能自定义，版权所有年份不能自定义，只能是2022，望改进。

**Comment by bhaoo** [comment]
好的~感谢建议

**Comment by only-matthew** [comment]
之前已经自己修改了源码更改了版权所有，但是如果更新就需要重新修改。see优化啥时候开始？

**Comment by bhaoo** [comment]
✨ 新增 站点版权信息自定义(https://github.com/bhaoo/Cuckoo/commit/520377082ee82a2c93055236977370c98b00e9a8)
