### ISSUE TITLE
友链显示异常

### ISSUE THREAD

**Issue by AkulaKirov** [bhaoo/Cuckoo#47]
**问题出处：**

这个问题出现在哪个功能上？

友情链接功能

**问题结果：**

触发问题后造成了什么效果及影响？

友情链接侧边栏报错
![图片](https://user-images.githubusercontent.com/33571798/166326258-670731de-42fc-4bdc-b88d-ec63ec621f20.png)

**预期结果：**

你觉得这个功能该怎么样？

谔谔 这还用说吗

**问题复现：**

你是怎么触发这个问题的？

尝试使用文档里给的Links插件和第三方维护Links插件 均触发此问题

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.3
- 数据库类型 / 版本：MySQL 5.6.50
- Typecho 版本：1.2.0
- 主题版本：（Release 标注的版本号，开发版则写 Dev.）2.0.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）Links
- 浏览器：（浏览器名称及版本号）FF 99.0.1

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

![图片](https://user-images.githubusercontent.com/33571798/166326552-712381ff-dab1-4be3-bf19-392688d54f70.png)

**补充信息：**

提供尽可能多的相关信息。

注释掉 `functions.php` 中 441-447 行报错会消失

**Comment by bhaoo** [comment]
使用release里面适配v2的Links插件哦！
