### ISSUE TITLE
9JOJOAPI无法访问，文章头图无法显示

### ISSUE THREAD

**Issue by MRNOBODY-ZST** [bhaoo/Cuckoo#49]
**问题出处：**

随机头图功能

**问题结果：**

无法显示随机头图

**问题复现：**

在选择9JOJOAPI时与OMGのAPI时候，无法正常访问

**配置与环境：**

- 问题页面：mrzst.top
- PHP 版本：7.4
- 数据库类型 / 版本：MySQL 5.7
- Typecho 版本：1.2.0
- 主题版本：2.0.1
- 使用的插件：none
- 浏览器：Google Chrome

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

9JOJOAPI无法访问

**Comment by bhaoo** [comment]
9JOJO源目前已经无法使用了，下个版本会进行移除，对于静态文件源的问题后续我再想想办法，你可以将jsdelivr源的`cdn.jsdelivr.com`改为`fastly.jsdelivr.com`作为临时解决办法（

**Comment by MRNOBODY-ZST** [comment]
好！

**Comment by MRNOBODY-ZST** [comment]
静态文件源可以让百度帮忙 有免费CDN
此外腾讯云的100G 10元CDN也不错 但是要国内备案域名

**Comment by MRNOBODY-ZST** [comment]
@bhaoo
