### ISSUE TITLE
[BUG]有关密码保护的bug

### ISSUE THREAD

**Issue by CX4A3** [bhaoo/Cuckoo#5]
作者您好！
使用过程中我发现，设置密码保护的文章，如果被显示在主页，或者以卡片的形式显示在某个页面的时候，文章的一部分内容会无视密码保护而直接显示在卡片上。

**Comment by bhaoo** [comment]
这边测试没有出现这个问题的，你看看后台是不是登录了，登录后台后前台是会直接显示文章的哦！如果还有出现问题请发一下截图和链接（可以发给邮箱 i#bhao.top 给我）！

**Comment by bhaoo** [comment]
如果还有出现问题可以发送邮件给我(附上截图和链接),目前我先关闭了
