### ISSUE TITLE
追番本地有缓存文件后就一直提示加载失败

### ISSUE THREAD

**Issue by LoCCai** [bhaoo/Cuckoo#51]
大佬帮忙看一下，是不是我curl的问题

**问题出处：**
追番
这个问题出现在哪个功能上？

**问题结果：**
加载失败
触发问题后造成了什么效果及影响？
网页无法查看
**预期结果：**

你觉得这个功能该怎么样？

**问题复现：**

你是怎么触发这个问题的？

**配置与环境：**

- 问题页面：https://blog.loccai.top/index.php/16.html
- PHP 版本：80
- 数据库类型 / 版本：MySQL
- Typecho 版本：最新
- 主题版本：（Release 标注的版本号，开发版则写 Dev.）
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by bhaoo** [comment]
你可以康康你的破站追番有没有设置公开

**Comment by LoCCai** [comment]
打开了公开，本地没有缓存文件的情况下，第一次打开页面必定正常显示追番，然后刷新就提示加载失败

**Comment by LoCCai** [comment]
![image](https://user-images.githubusercontent.com/105721394/172124081-07248061-252e-4675-a65f-140451587772.png)
![image](https://user-images.githubusercontent.com/105721394/172124160-07d46e9a-d8d5-4c16-bf20-911eb3c908bb.png)
![image](https://user-images.githubusercontent.com/105721394/172124294-e878bfd4-a0ac-460b-8403-cdb20608c450.png)
![image](https://user-images.githubusercontent.com/105721394/172124335-224223e5-f30b-4df4-a842-9df778c7dae8.png)
![image](https://user-images.githubusercontent.com/105721394/172124383-0bf50350-1a8e-4a09-a695-c01c27bab1a2.png)

**Comment by bhaoo** [comment]
将缓存文件的文件权限改为 777 试试看，可能是PHP无法获取缓存文件

**Comment by LoCCai** [comment]
并不行.......

**Comment by LoCCai** [comment]
我直接把检测改为发现本地缓存文件就删除，无非多访问鼠鼠几次，应该也没人会闲的没事一直看这个

**Comment by bhaoo** [comment]
好家伙 bksn
