### ISSUE TITLE
关于应用栏的建议

### ISSUE THREAD

**Issue by TheFunny** [bhaoo/Cuckoo#53]
**这个想法是哪个方面的？**

UI 界面 

**这个想法要做到什么？**

避免应用栏标题文字与下方内容重合导致混淆。

**这个想法能为项目提供什么帮助？**

界面更美观（？大概

**是否有具体的实现思路？**

给应用栏增加颜色、不透明度。

**补充信息：**

![image](https://user-images.githubusercontent.com/26841179/181211453-7085242c-a671-4ec7-a0f5-ae97692ed496.png)

对比度较低的情况：
![image](https://user-images.githubusercontent.com/26841179/181211256-20d3a1d4-6889-4006-bbf4-a7715721b7a6.png)

**Comment by dunxuan** [comment]
已修复 🔨 修复 亮色模式时浅色背景下的白色图标看不清楚的问题
https://github.com/bhaoo/Cuckoo/commit/58801e649043abdc9e37c1a50750a2c3c281f8c7
