### ISSUE TITLE
静态资源自定义 字体链接可以访问，但报错

### ISSUE THREAD

**Issue by weiliangrong2022** [bhaoo/Cuckoo#55]
> 反馈前请确认你的 **CDN或浏览器缓存已经清除**，你没有 **修改相关源代码** ，若你已经确认为项目中的问题，请删除这段文本，继续完成你的反馈

**问题出处：**

静态资源自定义

**问题结果：**

图标消失

**预期结果：**

加快网站访问速度

**问题复现：**

使用静态资源自定义

**配置与环境：**

- 问题页面：https://blog.wlr.lol/
- PHP 版本：74
- 数据库类型 / 版本：mysql 5.6.51
- Typecho 版本：1.2
- 主题版本：2.0.1
- 使用的插件：waterMark ZhiNianCommentNotifier Sticky Sitemap ShortLinks Passport 维护模式 Links HideTool DPlayer Beblank BaiduSubmit AliceStyle AutoTags Accessories AAEditor 
- 浏览器：（浏览器名称及版本号）

**截图（若有）**

![Screenshot_2022-07-31-15-34-37-16.jpg](https://tu.wlr.lol/i/2022/07/31/62e63229a90b0.jpg)

**补充信息：**

提供尽可能多的相关信息。

**Comment by bhaoo** [comment]
应该是你的字体文件所在的对象存储没有设置跨域导致的问题哦

**Comment by weiliangrong2022** [comment]
解决了，感谢
