### ISSUE TITLE
关于友链插件 Links 的问题

### ISSUE THREAD

**Issue by TheFunny** [bhaoo/Cuckoo#57]
**问题出处：**

Links 插件。

**问题结果：**

1. 禁用 Links 插件后再次开启会提示数据库错误。
2. Links 插件年久失修，存在越权漏洞。
3. 访问友链页面报错，`shuffle()` 函数参数错误。

**预期结果：**

正常工作，访问友链页面正常，启用/禁用插件正常。

**问题复现：**

1. 禁用/启用 Links 插件。
2. 参考补充信息中的来源。
3. 访问友链页面。

**配置与环境：**

- 问题页面：[链接](https://yoursfunny.top/links.html)
- PHP 版本：8.0.21
- 数据库类型 / 版本：MySQL 5.5.62
- Typecho 版本：1.2.0
- 主题版本：2.0.2
- 使用的插件：Links，MathJax
- 浏览器：Chrome 104.0.5112.81

**截图（若有）**

- 友链页面报错
![image](https://user-images.githubusercontent.com/26841179/184103546-67fad57e-1411-4849-9d21-de0070790ee6.png)

**补充信息：**

- 数据库错误 Bug 修复方法来源[网页](http://www.imhan.com/archives/typecho_links_20141214/#comment-1223)。
- 越权漏洞来源[网页](https://wischu.com/archives/791.html)。
- 关于友链页面报错问题，若友链显示数量不设置为0，则任何显示侧边栏友链的页面都会触发该问题。
   - 关于该问题的修复方法，可以在使用 `shuffle()` 函数前添加 `if(!isset($Links)) { $Links = []; }` 解决。

**Comment by TheFunny** [comment]
刚刚才看到 issue，友链报错的问题似乎解决了，但另外两个问题仍然存在？
此外，文档里面没有更新新的 Links 插件地址。

**Comment by TheFunny** [comment]
另外，短代码的可拓展面板在我的配置下似乎也不可用。（是不是该另外开个issue（

**Comment by bhaoo** [comment]
> 另外，短代码的可拓展面板在我的配置下似乎也不可用。（是不是该另外开个issue（

另外一个吧 thanks！

**Comment by bhaoo** [comment]
> 刚刚才看到 issue，友链报错的问题似乎解决了，但另外两个问题仍然存在？
> 此外，文档里面没有更新新的 Links 插件地址。

好的 收到啦 待我去看看

**Comment by bhaoo** [comment]
你可以试试越权这个问题的复现，我在 **Typecho 1.2.0** 版本 似乎无法复现问题

**Comment by TheFunny** [comment]
> 你可以试试越权这个问题的复现，我在 **Typecho 1.2.0** 版本 似乎无法复现问题

刚刚测试了下，我这也无法复现，也许修复了？

**Comment by bhaoo** [comment]
那就只有 启动数据库建立错误 的 BUG了是么

**Comment by TheFunny** [comment]
> 那就只有 启动数据库建立错误 的 BUG了是么

应该是的

**Comment by dunxuan** [comment]
现在有个社区版好像也不错[https://github.com/typecho-fans/plugins/tree/master/Links](https://github.com/typecho-fans/plugins/tree/master/Links)
