### ISSUE TITLE
关于可拓展面板不可用的问题

### ISSUE THREAD

**Issue by TheFunny** [bhaoo/Cuckoo#58]
**问题出处：**

短代码中的可拓展面板。

**问题结果：**

无法使用可拓展面板。

**预期结果：**

正常解析并显示可拓展面板。

**问题复现：**

在撰写文章页面添加可拓展面板的短代码。

**配置与环境：**

- 问题页面：本地测试
- PHP 版本：8.0.2
- 数据库类型 / 版本：MySQL 5.7.26
- Typecho 版本：1.2.0
- 主题版本：2.0.2
- 使用的插件：Links
- 浏览器：Chrome 104.0.5112.81

**截图（若有）**

![image](https://user-images.githubusercontent.com/26841179/184343166-88e27684-ba39-4b2d-9626-e8583451ea6e.png)

![image](https://user-images.githubusercontent.com/26841179/184343099-f67efa35-dd4c-4210-a3c4-6b0a6a7fd4e8.png)

**补充信息：**

bilibili 视频的的短代码是可用的。

**Comment by TheFunny** [comment]
刚刚试了试 只要有 class 属性就能用了

**Comment by bhaoo** [comment]
文档没补充好属于是
