### ISSUE TITLE
关于目录中的标题层级的问题

### ISSUE THREAD

**Issue by TheFunny** [bhaoo/Cuckoo#59]
**问题出处：**

目录中现实的标题的层级。

**问题结果：**

本应相同层级的标题，在目录中显示为不同层级。

**预期结果：**

目录中的标题层级正常显示。

**问题复现：**

不好描述，看下面截图吧。

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.0.21
- 数据库类型 / 版本：MySQL 5.7.39
- Typecho 版本：1.2.0
- 主题版本：2.0.2
- 使用的插件：Links
- 浏览器：Chrome 104.0.5112.102

**截图（若有）**

![image](https://user-images.githubusercontent.com/26841179/185197824-3dff44a0-0625-4eea-adf2-cf2d1a219e85.png)
![image](https://user-images.githubusercontent.com/26841179/185197870-56d4077b-9d41-4eb8-93a4-082a012eb92c.png)

**补充信息：**

对于图一两种写法，显示出的目录都是图二的样式。

此外我还有一个问题，对于如下截图中的写法，会如何处理呢？
![image](https://user-images.githubusercontent.com/26841179/185199716-e6094228-bf02-45ec-bd4b-4dcd9a5bd3ca.png)

**Comment by LemonPrefect** [comment]
请参照 markdown-lint 编写规范的文档。
[lint](https://github.com/updownpress/markdown-lint/blob/master/rules/001-header-increment.md) 
issue 部分不符合规范，从而导致了异常。
@bhaoo @TheFunny
