### ISSUE TITLE
[建议]图片格式的改进

### ISSUE THREAD

**Issue by rsj123** [bhaoo/Cuckoo#6]
建议将资源图片格式改成webp，这样可以极大减小图片大小，即使是loading的动态图用gif有500k，但是webp只有100k多，加载速度会快很多
（说白了就是我的小水管太垃圾了

**Comment by bhaoo** [comment]
好的！收到你的建议啦！待我看看

**Comment by bhaoo** [comment]
目前大多浏览器还没有兼容webp，所以目前不会转换啦

**Comment by rsj123** [comment]
https://caniuse.com/#feat=webp
可以参考下这里，目前webp的支持率大概是79.49%，只有ie和Safari没有支持，可以另外做兼容，毕竟webp是个很节约的方法

**Comment by SatoSouta** [comment]
> https://caniuse.com/#feat=webp
> 
> 可以参考下这里，目前webp的支持率大概是79.49%，只有ie和Safari没有支持，可以另外做兼容，毕竟webp是个很节约的方法

我Safari党。

**Comment by bhaoo** [comment]
使用 Safari 和 IE 的用户还是比较多的，特别的 Safari ，所以目前不会将图片格式改为 webp 了哦
