### ISSUE TITLE
主题阅读文章时，双栏设计使得阅读体验不好，希望能够被选择为单栏

### ISSUE THREAD

**Issue by lishufood** [bhaoo/Cuckoo#60]
> 注意： **请确认你的想法能被多数人接受且能使项目越来越好哦！** 若你的想法符合这个条件，请删除这段文本，继续完成你的反馈哦

**这个想法是哪个方面的？**

UI 界面

**这个想法要做到什么？**

希望可以在后台增加一个控制选项：在阅读文章时，排版为单栏（目前为双栏）

**这个想法能为项目提供什么帮助？**

更专注的阅读，在长文的情况下，双栏显示的内容窄、小，我认为体验一般

**是否有具体的实现思路？**

目前暂时我不会，，我想应该可以通过改html文件来实现，不会很难。

**补充信息：**

如果没有被采纳的话，在了解学习后，应该会自己动手更改。改完后会提交代码于这的，

**Comment by LemonPrefect** [comment]
对于长文章来说不可或缺的兴许还有目录，单栏势必会丢失现有跟随目录。除此之外，一行其实不适合显示很多字，否则看起来会很累。
