### ISSUE TITLE
内置随机图片 API 失效

### ISSUE THREAD

**Issue by weilinfox** [bhaoo/Cuckoo#63]
**随机图片 API ：**

OMGのAPI 似乎在维护而不可使用， 9JOJO 由于 Referer 原因返回 403 （现在貌似不卡 Referer 但是会偶现 403 的样子）。

**问题结果：**

主题内置随机图片源不可使用。

**配置与环境：**

- PHP 版本：7.4
- 数据库类型 / 版本：PostgreSQL
- Typecho 版本：2.0.1
- 浏览器：Edge 106.0.1370.42 (正式版本) (64 位) Firefox 107.0a1 (2022-10-16) (64-bit)

**截图（若有）**

OMGのAPI

![image](https://user-images.githubusercontent.com/54651938/196104127-8f7dab7f-102a-47ac-9fd4-2047a3e19891.png)

9JOJO

![image](https://user-images.githubusercontent.com/54651938/196103886-81937c21-1525-4e4d-be9e-67c05d8d7845.png)

**Comment by bhaoo** [comment]
稍等...晚些我去看看哪个修复了更新下~

**Comment by bhaoo** [comment]
9JOJO 的已经修复了哦 OMGのAPI 暂时用不了了
