### ISSUE TITLE
首页默认背景图

### ISSUE THREAD

**Issue by 3820787** [bhaoo/Cuckoo#65]
**背景图**

在手机上显示的背景图很糟糕，模糊并且随滑动慢慢的以几帧滑动。希望可以在手机端展示完整的背景图
**这个想法要做到什么？**

**可以提高手机端访问体验**

**Comment by inwinter04** [comment]
关于背景图模糊，请查看是否在后台中开启了背景图片高斯模糊
_（关于此功能介绍）_
```
选择"0"即为关闭高斯模糊哦！若网站动画较卡可设置为"0"
```
关于滑动时背景图片不适配，此问题我尚未遇到过，请检查换一个浏览器是否正常。目前我使用夸克与Edge浏览器。或者你可以打开我的博客查看是否存在该问题[冬天的小窝](https://www.iamdt.cn)

**Comment by 3820787** [comment]
是的，在你的博客首页也出现了同样的问题，这被我录下在附属视频内

**Comment by 3820787** [comment]
我使用的是safari 浏览器

**Comment by 3820787** [comment]
http://pan.shyyyun.cn/file.php?hash=9eb7a1a644394bc170dbe8cf4c9fc9fe这个是录制视频的网盘链接，我无法将其上传到GitHub上

**Comment by bhaoo** [comment]
来来来来来来来来来来力！问下这个问题还存在么？

**Comment by bhaoo** [comment]
已经修复力！
