### ISSUE TITLE
启用Links插件后主页报错500

### ISSUE THREAD

**Issue by QSlotus** [bhaoo/Cuckoo#67]
**问题出处：**

友链功能

**问题结果：**

启用Links插件后，博客主页报错  `500 Database Query Error`

**预期结果：**

Links插件正常工作。

**问题复现：**

1. 启用Links插件。
2. 访问博客主页。

**配置与环境：**

- 问题页面：null
- PHP 版本：7.4.8
- 数据库类型 / 版本：MySQL
- Typecho 版本：1.2.0
- 主题版本：2.0.2
- 使用的插件：Links
- 浏览器：Microsoft Edge 108.0.1462.76

**截图（若有）**
![XX5P(PIM}H7_JQ@~~0NM}AB](https://user-images.githubusercontent.com/109905194/211564669-70eefce5-e716-4674-a247-f177ee322e64.png)

**补充信息：**
- 于 config.inc.php 添加 `define('__TYPECHO_DEBUG__', true);`后，主页侧边栏友情链接处报错信息如下：
- ![image](https://user-images.githubusercontent.com/109905194/211567509-bcf624cb-b7c2-40b1-b248-d9bd8c4f1f52.png)
- 完整信息：
- 
![image](https://user-images.githubusercontent.com/109905194/211567616-191eacaf-31db-4bba-9220-c6b29fd6a8fd.png)

**Comment by bhaoo** [comment]
emmm 报错提示是表不存在哦，你到数据库去康康？

**Comment by QSlotus** [comment]
> emmm 报错提示是表不存在哦，你到数据库去康康？

啊对了，昨天忘记说了，我去数据库看了下，在启用插件时没有生成typecho_links这张表＞︿＜
