### ISSUE TITLE
友链功能相关问题

### ISSUE THREAD

**Issue by Annran233** [bhaoo/Cuckoo#84]
**问题出处：友链功能异常**

**问题结果：于首页友情链接处及友链独立页面显示友链时，显示友链和一段Warning：Warning: shuffle() expects parameter 1 to be array, null given in /data/wwwroot/mnbt.1294021a0/usr/themes/Cuckoo/functions.php on line 472**

**预期结果：正常显示友链**

**问题复现：按照文档安装Links插件，添加友链。**

**配置与环境：**

- 问题页面：https://ayx.xn--kivy66br3pu7d.ink/friends.html
- PHP 版本：PHP 7.4
- 数据库类型 / 版本：MySQL 5.6.50
- Typecho 版本：1.2.1
- 主题版本：2.0.2
- 使用的插件：Links,Sitemap,Notion
- 浏览器：Google Chrome Android Beta115.0.5790.85 (正式版本) beta (32 位元) 

**截图（若有）**

https://pic.bibiu.cc/2023/08/05/64ce6aa703470.jpg
https://pic.bibiu.cc/2023/08/05/64ce6aa79ef3b.jpg

**补充信息：尝试文档内给出的Links插件，寒泥的Links插件，Typecho Fans插件目录中的Links插件，均未解决问题。**

**Comment by KearChen** [comment]
替换Links函数
function Links($type = 0) {
  // 检查是否存在"Links"插件并已激活
  if (array_key_exists("Links", Typecho_Plugin::export()['activated'])) {
    $shuffle = Helper::options()->linksshuffle; // 获取是否启用链接随机排序的设置
    $link_limit = Helper::options()->linksIndexNum; // 获取链接显示数量的设置
    $Links = []; // 初始化链接数组

    if ($type == 0) {
      // 获取链接输出内容（类型0）
      $Links = Links_Plugin::output("
      <a target='_blank' class='links-url' href='{url}'>
        <div class='mdui-col-sm-6'>
          <div class='links-card mdui-shadow-10'>
            <div class='links-img'><img class='mdui-img-circle' src='{image}'/></div>
            <div class='links-name links-text'>{name}</div>
            <div class='links-describe links-text'>{description}</div>
          </div>
        </div>
      </a>");
    } elseif ($type == 1) {
      // 获取链接输出内容（类型1）
      $Links = Links_Plugin::output("
      <div class='mdui-col'>
        <a target='_blank' href='{url}'>
         <li class='mdui-list-item mdui-ripple sidebar-module-list'>
            <div class='sidebar-reply-text'>{name}</div>
          </li>
        </a>
      </div>");
    }
    
    // 如果启用了随机排序，并且"open"在随机排序数组中
    if ($shuffle && in_array('open', $shuffle)) {
      shuffle($Links); // 随机排序链接
    }

    // 确保$Links始终是数组，即使在输出过程中没有找到链接
    if (!is_array($Links)) {
      $Links = [];
    }

    // 根据链接数量设置限制，遍历输出链接
    $link_limit = (!$type || $link_limit > count($Links)) ? count($Links) : $link_limit;
    for ($i = 0; $i < $link_limit; $i++) {
      echo $Links[$i]; // 输出链接
    }
  }
}

**Comment by bhaoo** [comment]
Links 插件魔改过，文档没及时更新非常抱歉！
试试 Github Release 里面适配 V2 的 Links 插件吧
