### ISSUE TITLE
文章图片的问题

### ISSUE THREAD

**Issue by imzlh** [bhaoo/Cuckoo#86]
我就不按照模板回答了.
1. CSS问题：文章图片大小0x0
  应该这么设置:
```
.mdui-card-media {
    position: relative;
}
```
2.当我使用自定义CDN图片时，几个字符（rand）被替换了
源链接是:https://imzlh.top:8443/@random/

![image](https://github.com/bhaoo/Cuckoo/assets/114276136/42d66ada-1df5-4a37-bf16-144f535186ef)

建议改成**{{random}}**更好，防止误匹配

**Comment by bhaoo** [comment]
感谢你的反馈！

Answer:

1. 默认带有这个设置的，可以再详细一点么？
2. 错误的匹配导致的，在 开发版 进行修复啦！你也可以尝试直接在你代码中进行修改 `functions.php` L225 处的内容进行修复。


```php
// before
$output = preg_replace('{rand}', $rand, $setting_cdn);
// after
$output = preg_replace('/{rand}/', $rand, $setting_cdn);
```
