### ISSUE TITLE
评论、回复会打乱代码块布局

### ISSUE THREAD

**Issue by 2WY0** [bhaoo/Cuckoo#9]
1.每评论、回复一次，文章的代码块都会增加无用的行数，两次多次评论、回复后代码块布局极乱。

2.回复评论后会自动再发送一遍，造成二次重复评论。 
![Screenshot_2020-04-16-00-54-33-322_mark via](https://user-images.githubusercontent.com/41849402/79366034-10a3d280-7f7e-11ea-8c3b-88f5a7961e18.png)
![Screenshot_2020-04-16-00-54-51-984_mark via](https://user-images.githubusercontent.com/41849402/79366047-139ec300-7f7e-11ea-8920-9a0c217aa776.png)

@bhaoo

**Comment by bhaoo** [comment]
v1.0.5已经修复啦
